### PR TITLE
Fix an issue with library loading.

### PR DESCRIPTION
**Pull request by FreddieWitherden**
This was a bug I introduced in a previous commit.

### CODE REVIEW

**Comment by mjklemm** [comment]
Hi Freddie,

On my machine, the tests still behave the same way.

Cheers,
        -michael

Dr.-Ing. Michael Klemm
Senior Application Engineer
Software and Services Group
Developer Relations Division
Phone    +49 89 9914 2340
Cell         +49 174 2417583

**Comment by FreddieWitherden** [comment]
Given it another kick or two.  Now on my box (with a single Phi):

```
...................................................................................................F.........
======================================================================
FAIL: test_library_device_mismatch (offload_library_tests.OffloadLibraryTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/freddie/Programming/pymic/tests/helper.py", line 52, in wrapper
    "Could not find multiple Xeon Phi coprocessors "
AssertionError: Could not find multiple Xeon Phi coprocessors to test with

----------------------------------------------------------------------
Ran 109 tests in 83.910s

FAILED (failures=1)```

**Comment by mjklemm** [comment]
Is this with the single-line patch from this pull request?

**Comment by FreddieWitherden** [comment]
I amended the pull request so it is now 8 additions and 3 deletions.

**Comment by mjklemm** [comment]
Problem solved on my machine, too.  Thanks!

**Comment by FreddieWitherden** [comment]
Sorry for the noise :)

**Pull request merged**
